spring.application.name=api

# ===== CẤU HÌNH DATABASE THÔNG MINH (LOCAL & CLOUD) =====
# Cú pháp ${TÊN_BIẾN:Giá_trị_dự_phòng}
# Khi lên Render, nó sẽ đọc DB_URL. Còn chạy ở máy bạn, nó dùng localhost:3307
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/livescore_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== PHÉP THUẬT AUTO TẠO BẢNG =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect